databases:
  - name: playto-db
    databaseName: playto
    user: playto_user

services:
  - type: web
    name: playto-backend
    env: python
    buildCommand: |
        cd backend
        pip install -r requirements.txt
        python manage.py collectstatic --noinput
        python manage.py migrate
    startCommand: |
        cd backend
        gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: playto-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

  - type: web
    name: playto-frontend
    env: static
    buildCommand: |
        cd frontend
        npm install
        npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
